### ISSUE TITLE
How to get started? Example webpack config fails.

### ISSUE THREAD

**Issue by davidmaxwaterman** [hiikezoe/web-ext-webpack-plugin#54]
I'm trying to make use of this plugin, hopefully it will include the needed files from node_modules into the extensions zip file - but I just get an error below. Could you point me in the right direction?

My webpack.config.mjs file is:

```
import WebExtPlugin from 'web-ext-plugin';

module.exports = {
  plugins: [new WebExtPlugin({ sourceDir: 'extension-dist' })],
};
```

but:

```
$ npx webpack                                                                                                                                                                    master
[webpack-cli] Failed to load '/Users/davidmaxwaterman/z/davidmaxwaterman/sync-gun/webpack.config.mjs' config
[webpack-cli] ReferenceError: module is not defined in ES module scope
    at file:///Users/davidmaxwaterman/z/davidmaxwaterman/sync-gun/webpack.config.mjs:3:1
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async WebpackCLI.tryRequireThenImport (/Users/davidmaxwaterman/z/davidmaxwaterman/sync-gun/node_modules/webpack-cli/lib/webpack-cli.js:213:26)
    at async loadConfigByPath (/Users/davidmaxwaterman/z/davidmaxwaterman/sync-gun/node_modules/webpack-cli/lib/webpack-cli.js:1404:27)
    at async WebpackCLI.loadConfig (/Users/davidmaxwaterman/z/davidmaxwaterman/sync-gun/node_modules/webpack-cli/lib/webpack-cli.js:1510:38)
    at async WebpackCLI.createCompiler (/Users/davidmaxwaterman/z/davidmaxwaterman/sync-gun/node_modules/webpack-cli/lib/webpack-cli.js:1785:22)
    at async WebpackCLI.runWebpack (/Users/davidmaxwaterman/z/davidmaxwaterman/sync-gun/node_modules/webpack-cli/lib/webpack-cli.js:1890:20)
```

My package.json file is:

```
{
  "name": "sync-gun",
  "version": "0.0.1",
  "description": "Investigation into syncing with gun.",
  "main": "background-script.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "gun": "^0.2020.1238"
  },
  "devDependencies": {
    "eslint": "^8.24.0",
    "web-ext-plugin": "^2.5.1",
    "webpack-cli": "^4.10.0"
  }
}
```

and:

```
$ npm ls
sync-gun@0.0.1 /Users/davidmaxwaterman/z/davidmaxwaterman/sync-gun
├── eslint@8.24.0
├── gun@0.2020.1238
├── web-ext-plugin@2.5.1
└── webpack-cli@4.10.0
```

This is how the files are in my repo:

```
$ ls -1                                                                                                                                                                          master
background-page.html
background-script.js
manifest.json
node_modules/
package-lock.json
package.json
web-ext-artifacts/
webpack.config.mjs
```

**Comment by birtles** [comment]
Hi! Sorry for the delay.

I think the issue is that you are using an `.mjs` file with `exports.module`. I believe that when using ESM, your `webpack.config.mjs` file should look like:

```js
import WebExtPlugin from 'web-ext-plugin';

export default {
  plugins: [new WebExtPlugin({ sourceDir: 'extension-dist' })],
};
```

**Comment by davidmaxwaterman** [comment]
Thanks, but I found a different solution.

**Comment by ascariandrea** [comment]
> Thanks, but I found a different solution.

@davidmaxwaterman what was your solution? I'm having the same issue with `.ts`.

```
[webpack-cli] Failed to load '[...]/extension/webpack.config.ts' config
[webpack-cli] TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for [...]/extension/webpack.config.ts
    at new NodeError (node:internal/errors:387:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:75:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:117:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:601:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:476:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

**Comment by davidmaxwaterman** [comment]
I gave up on webpack and instead used https://github.com/samrum/vite-plugin-web-extension
